version: "3"

services:
  postgres:
    image: "postgres:latest"
    container_name: "starter-postgres"
    volumes:
      - './volumes/postgres:/var/lib/postgresql/data'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME:-starter}
      POSTGRES_USER: ${DB_USERNAME:-starter}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}

  api:
    image: "node:latest"
    env_file: '.env.docker'
    container_name: "starter-api"
    volumes:
      - "./:/source"
    working_dir: /source
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    command: bash -c "yarn && yarn dev"
